# load data

In [2]:
import os
import numpy as np
import pandas as pd

# if you use `ios` or `windows`, you need to change the `REPO_PATH` to your own path
REPO_PATH = os.path.dirname(os.path.dirname(os.getcwd()))

train_data_preprocessed = pd.read_csv(
    os.path.join(REPO_PATH, "zqy", "temp", "train_data_fillna_drop_norm.csv")
)
test_data_preprocessed = pd.read_csv(
    os.path.join(REPO_PATH, "zqy", "temp", "test_data_fillna_drop_norm.csv")
)


In [3]:
train_data_preprocessed.shape, test_data_preprocessed.shape

((61866, 3695), (18134, 3695))

In [4]:
train_data_preprocessed.head(3)

X0        X1        X2   X3            X4            X5  \
0  1.709604 -0.364987 -1.562489  0.0  9.770206e-16  1.243610e-15   
1  1.709604 -0.364987 -0.859708  0.0  9.770206e-16  1.243610e-15   
2  1.333118 -1.432679 -1.588871  0.0  9.770206e-16  1.243610e-15   

             X6        X7        X8        X9  ...         X3796     X3797  \
0 -2.221561e+00 -1.618875 -1.514485 -1.218867  ...  1.956724e-15  0.000000   
1  8.961731e-16 -1.406030 -1.266209 -1.218867  ... -2.723617e+00 -2.784325   
2  8.961731e-16 -1.772480 -1.633739 -1.762651  ...  1.956724e-15  0.000000   

          X3798     X3799         X3800         X3801         X3802  \
0  5.428685e-16  0.000000 -1.630523e-15 -1.087010e-15 -1.621701e-15   
1  4.535885e+00  2.914316  3.404360e+00  4.161721e+00  3.311772e+00   
2  5.428685e-16  0.000000 -1.630523e-15 -1.087010e-15 -1.621701e-15   

          X3803         X3804         X3805  
0  1.620792e-15 -1.089747e-15 -1.104692e-15  
1  2.713803e+00  2.382499e+00  2.702521e+00  
2  1.620792e-15 -1.089747e-15 -1.104692e-15  

[3 rows x 3695 columns]

In [5]:
test_data_preprocessed.head(3)

X0        X1        X2   X3            X4            X5  \
0 -1.450864 -1.432679 -0.020007  0.0  9.770206e-16  1.243610e-15   
1  0.047310  1.381808  0.155341  0.0  9.770206e-16  1.243610e-15   
2 -1.450864  0.797930  0.158208  0.0  9.770206e-16  1.243610e-15   

             X6        X7        X8        X9  ...         X3796  X3797  \
0  8.961731e-16 -0.711873  0.503163  1.463917  ...  1.956724e-15    0.0   
1  8.961731e-16  1.521253  1.613779  1.189941  ...  1.956724e-15    0.0   
2  8.961731e-16 -0.111994 -0.207470 -0.235015  ...  1.956724e-15    0.0   

          X3798  X3799         X3800         X3801         X3802  \
0  5.428685e-16    0.0 -1.630523e-15 -1.087010e-15 -1.621701e-15   
1  5.428685e-16    0.0 -1.630523e-15 -1.087010e-15 -1.621701e-15   
2  5.428685e-16    0.0 -1.630523e-15 -1.087010e-15 -1.621701e-15   

          X3803         X3804         X3805  
0  1.620792e-15 -1.089747e-15 -1.104692e-15  
1  1.620792e-15 -1.089747e-15 -1.104692e-15  
2  1.620792e-15 -1.089747e-15 -1.104692e-15  

[3 rows x 3695 columns]

In [6]:
# path = "zqy/temp/2024年四川省大学生数据科学与统计建模竞赛/训练集/train_target.csv"
path = os.path.join('zqy', 'temp', 'train_target.csv')
train_target = pd.read_csv(os.path.join(REPO_PATH, path))
train_target

idx  date    y
0          0     7  0.0
1          1     7  0.0
2          2     8  0.0
3          3     7  0.0
4          4     7  0.0
...      ...   ...  ...
61861  79995    21  0.0
61862  79996    21  0.0
61863  79997    21  0.0
61864  79998    21  0.0
61865  79999    21  0.0

[61866 rows x 3 columns]

In [7]:
train_target_drop = train_target.drop(columns=["idx", "date"]).astype(int)
train_target_drop   

y
0      0
1      0
2      0
3      0
4      0
...   ..
61861  0
61862  0
61863  0
61864  0
61865  0

[61866 rows x 1 columns]

In [8]:
np.unique(train_target_drop.values, return_counts=True)

(array([0, 1]), array([50526, 11340]))

# MLP

In [20]:
import tensorflow as tf
import tensorflow.keras as keras

model = keras.Sequential([
    keras.layers.Dense(1800, activation='relu', input_shape=(train_data_preprocessed.shape[1],)),
    # keras.layers.Dense(5000, activation='relu'),
    keras.layers.Dense(2560, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1024, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dropout(0.2),
    # keras.layers.Dense(2, activation='softmax')
    keras.layers.Dense(1, activation='sigmoid')
])

model.summary()

/home/zqy/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 1800)           │     6,652,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 2560)           │     4,610,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 2560)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1024)           │     2,622,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 256)            │       262,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,165,729 (54.04 MB)

 Trainable params: 14,165,729 (54.04 MB)

 Non-trainable params: 0 (0.00 B)

In [8]:
class_weight = {}
class_cnt = np.unique(train_target_drop, return_counts=True)
for i in range(len(class_cnt[0])):
    class_weight[i] = class_cnt[1].sum() / class_cnt[1][i]
class_weight, class_cnt

({0: 1.2244389027431422, 1: 5.455555555555556},
 (array([0, 1]), array([50526, 11340])))

In [9]:
train_target_one_hot = pd.get_dummies(train_target_drop, columns=['y'])
train_target_one_hot = train_target_one_hot.values
train_target_one_hot = train_target_one_hot.astype(int)
train_target_one_hot, train_target_one_hot.shape, train_data_preprocessed.shape

(array([[1, 0],
        [1, 0],
        [1, 0],
        ...,
        [1, 0],
        [1, 0],
        [1, 0]]),
 (61866, 2),
 (61866, 3695))

In [26]:
from tensorflow.keras.metrics import AUC, F1Score

# Initialize the weights you want to set
initial_weights = [np.random.rand(*w.shape) for w in model.get_weights()]
model.set_weights(initial_weights)

model.compile(
    optimizer="adam",
    # loss=keras.losses.CategoricalCrossentropy(from_logits=False),
    loss=keras.losses.BinaryCrossentropy(from_logits=False),
    metrics=["accuracy", "auc", F1Score(average="micro"), F1Score(average="macro")],
)
model.fit(
    train_data_preprocessed,
    # train_target_one_hot,
    train_target_drop,
    epochs=60,
    shuffle=True,
    # class_weight=class_weight,
    batch_size=32,
    validation_split=0.2,
)

Epoch 1/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 90s 58ms/step - accuracy: 0.3289 - auc: 0.5010 - f1_score: 0.3046 - f1_score_1: 0.3046 - loss: 1686341248.0000 - val_accuracy: 0.8474 - val_auc: 0.5000 - val_f1_score: 0.0000e+00 - val_f1_score_1: 0.0000e+00 - val_loss: 7740903.0000
Epoch 2/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 89s 57ms/step - accuracy: 0.6638 - auc: 0.4998 - f1_score: 0.2113 - f1_score_1: 0.2113 - loss: 15511708.0000 - val_accuracy: 0.8474 - val_auc: 0.5000 - val_f1_score: 0.0000e+00 - val_f1_score_1: 0.0000e+00 - val_loss: 2179317.7500
Epoch 3/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 89s 57ms/step - accuracy: 0.6726 - auc: 0.5024 - f1_score: 0.2090 - f1_score_1: 0.2090 - loss: 4338165.0000 - val_accuracy: 0.8474 - val_auc: 0.5000 - val_f1_score: 0.0000e+00 - val_f1_score_1: 0.0000e+00 - val_loss: 600758.0000
Epoch 4/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 89s 57ms/step - accuracy: 0.6694 - auc: 0.4979 - f1_score: 0.2030 - f1_score_1: 0.2030 - loss: 1128221.1250 - val_accuracy: 0.8474 - val_au

KeyboardInterrupt: 

## prediction

In [24]:
test_data = pd.read_csv("/home/zqy/learningFile/sichuan/zqy/temp/2024年四川省大学生数据科学与统计建模竞赛/测试集/test_data.csv")

In [26]:
# Predict the probabilities
predictions = model.predict(test_data_preprocessed)

# Convert probabilities to binary values (0 or 1) using a threshold of 0.5
binary_predictions = (predictions > 0.5).astype(int)

# Create a DataFrame with the results
output_binary = pd.DataFrame(binary_predictions, columns=["y_pred"])
output_binary["idx"] = test_data["idx"]
output_binary = output_binary[["idx", "y_pred"]]

567/567 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step


In [29]:
np.unique(output_binary.y_pred.values)

array([0])

In [21]:
output_pd.to_csv(
    os.path.join(REPO_PATH, "zqy", "output", "output.csv"),
    index=False,
    sep=",",
)

# XGBoost

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    train_data_preprocessed, train_target_drop, test_size=0.2, random_state=11
)

## single test

In [52]:
import xgboost as xgb
from sklearn.metrics import auc, roc_auc_score

model_xgb = xgb.XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    objective="binary:logistic",
    use_label_encoder=False,
    eval_metric=['logloss', 'auc', 'error'],
    tree_method = "hist", 
    device = "cuda",
)
model_xgb.fit(X_train, y_train, eval_set=[(X_test, y_test)])
print(roc_auc_score(y_test, model_xgb.predict_proba(X_test)))

/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [17:40:02] WARNING: /workspace/src/context.cc:43: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [17:40:02] WARNING: /workspace/src/context.cc:196: XGBoost is not compiled with CUDA support.
  warnings.warn(smsg, UserWarning)
/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [17:40:02] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[0]	validation_0-logloss:0.47819	validation_0-auc:0.61747	validation_0-error:0.18442
[1]	validation_0-logloss:0.47523	validation_0-auc:0.62336	validation_0-error:0.18442
[2]	validation_0-logloss:0.47241	validation_0-auc:0.63054	validation_0-error:0.18442
[3]	validation_0-logloss:0.47000	validation_0-auc:0.63521	validation_0-error:0.18442
[4]	validation_0-logloss:0.46792	validation_0-auc:0.63833	validation_0-error:0.18442
[5]	validation_0-logloss:0.46626	validation_0-auc:0.63863	validation_0-error:0.18442
[6]	validation_0-logloss:0.46465	validation_0-auc:0.64086	validation_0-error:0.18434
[7]	validation_0-logloss:0.46314	validation_0-auc:0.64377	validation_0-error:0.18418
[8]	validation_0-logloss:0.46185	validation_0-auc:0.64545	validation_0-error:0.18418
[9]	validation_0-logloss:0.46075	validation_0-auc:0.64732	validation_0-error:0.18410
[10]	validation_0-logloss:0.45958	validation_0-auc:0.64940	validation_0-error:0.18385
[11]	validation_0-logloss:0.45893	validation_0-auc:0.64945	valid

ValueError: y should be a 1d array, got an array of shape (12374, 2) instead.

## add weight

In [9]:
class_weight = {}
class_cnt = np.unique(train_target_drop, return_counts=True)
for i in range(len(class_cnt[0])):
    class_weight[i] = class_cnt[1].sum() / class_cnt[1][i]
class_weight, class_cnt

({0: 1.2244389027431422, 1: 5.455555555555556},
 (array([0, 1]), array([50526, 11340])))

In [10]:
train_target.head(3)

idx  date    y
0    0     7  0.0
1    1     7  0.0
2    2     8  0.0

we set the sample weight as :
$$
weight(i) = \frac{1}{1 + \exp\{-date\}}

In [11]:
train_target_date = train_target["date"].to_numpy()
train_target_date.max(), train_target_date.min()

(73, 1)

In [12]:
train_target_date

array([ 7,  7,  8, ..., 21, 21, 21])

In [13]:
alpha = 0.1
train_sample_weight = 1 / (1 + np.exp(- alpha * train_target_date))
train_sample_weight

array([0.66818777, 0.66818777, 0.68997448, ..., 0.89090318, 0.89090318,
       0.89090318])

In [14]:
train_class_weight = np.zeros(train_target_drop.shape[0])

for i in range(len(class_cnt[0])):
    train_class_weight[train_target_drop.to_numpy().flatten() == class_cnt[0][i]] = (
        class_weight[i]
    )
train_class_weight

array([1.2244389, 1.2244389, 1.2244389, ..., 1.2244389, 1.2244389,
       1.2244389])

In [15]:
train_together_weight = train_sample_weight * train_class_weight
train_together_weight

array([0.8181551 , 0.8181551 , 0.8448316 , ..., 1.09085651, 1.09085651,
       1.09085651])

In [16]:
from sklearn.model_selection import train_test_split

(
    X_train,
    X_test,
    y_train,
    y_test,
    w_class_train,
    w_class_test,
    w_together_train,
    w_together_test,
) = train_test_split(
    train_data_preprocessed,
    train_target_drop,
    train_class_weight,
    train_together_weight,
    test_size=0.2,
    random_state=11,
)

In [17]:
w_class_train.shape, w_class_test.shape, w_together_train.shape, w_together_test.shape

((49492,), (12374,), (49492,), (12374,))

## unit test

In [12]:
best_n_params, best_n_score

([{'gamma': 0,
   'learning_rate': 0.05,
   'max_depth': 2,
   'n_estimators': 800,
   'random_state': 42,
   'reg_alpha': 0.4,
   'reg_lambda': 10},
  {'gamma': 0.1,
   'learning_rate': 0.05,
   'max_depth': 2,
   'n_estimators': 800,
   'random_state': 42,
   'reg_alpha': 0.4,
   'reg_lambda': 10},
  {'gamma': 0.1,
   'learning_rate': 0.1,
   'max_depth': 2,
   'n_estimators': 400,
   'random_state': 42,
   'reg_alpha': 0.2,
   'reg_lambda': 10},
  {'gamma': 0,
   'learning_rate': 0.1,
   'max_depth': 2,
   'n_estimators': 400,
   'random_state': 42,
   'reg_alpha': 0.2,
   'reg_lambda': 10},
  {'gamma': 0.1,
   'learning_rate': 0.05,
   'max_depth': 2,
   'n_estimators': 800,
   'random_state': 42,
   'reg_alpha': 0.4,
   'reg_lambda': 1}],
 array([0.66952076, 0.66952076, 0.66922311, 0.66922311, 0.6691037 ]))

In [24]:
test_data_preprocessed.shape, train_data_preprocessed.shape

((18134, 3695), (61866, 3695))

In [17]:
best_params1 = {
    "gamma": 0,
    "learning_rate": 0.1,
    "max_depth": 2,
    "n_estimators": 430,
    # "n_estimators": 1200,
    "random_state": 42,
    "reg_alpha": 0.3,
}
best_params2 = {
    "gamma": 0,
    "learning_rate": 0.05,
    "max_depth": 2,
    # "n_estimators": 800,
    "n_estimators": 1200,
    "random_state": 42,
    "reg_alpha": 0.4,
    "reg_lambda": 10,
}
best_params3 = {
    "gamma": 0.1,
    "learning_rate": 0.05,
    "max_depth": 2,
    "n_estimators": 715,
    # "n_estimators": 1200,
    "random_state": 42,
    "reg_alpha": 0.4,
    "reg_lambda": 10,
}
best_params4 = {
    "gamma": 0.1,
    "learning_rate": 0.1,
    "max_depth": 2,
    # "n_estimators": 400,
    "n_estimators": 1200,
    "random_state": 42,
    "reg_alpha": 0.2,
    "reg_lambda": 10,
}

In [26]:
# use the best params to predict
import xgboost as xgb
from sklearn.metrics import auc, roc_auc_score

model_xgb = xgb.XGBClassifier(
    **best_params1,
    objective="binary:logistic",
    use_label_encoder=False,
    eval_metric='auc',
    tree_method = "hist", 
    device = "cuda",
    # early_stopping_rounds = 50,
)

# model_xgb.fit(X_train, y_train, eval_set=[(X_test, y_test)],)
# print(roc_auc_score(y_test, model_xgb.predict_proba(X_test)[:, 1]))

model_xgb.fit(train_data_preprocessed, train_target_drop, 
          sample_weight=train_together_weight,
            # sample_weight = train_class_weight,
            )

/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [17:59:55] WARNING: /workspace/src/context.cc:43: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [17:59:55] WARNING: /workspace/src/context.cc:196: XGBoost is not compiled with CUDA support.
  warnings.warn(smsg, UserWarning)
/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [17:59:55] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device='cuda', early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=0, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.1, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=2, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=430, n_jobs=None,
              num_parallel_tree=None, random_state=42, ...)

## grid test

In [1]:
import xgboost as xgb
from sklearn.metrics import auc, roc_auc_score
from sklearn.model_selection import GridSearchCV
import warnings

# don't print warnings
warnings.filterwarnings("ignore", category=UserWarning)


def grid_search_xgb(X, y, param_grid, weight, cv=5, scoring="roc_auc", n=5):
    grid_search = GridSearchCV(
        estimator=xgb.XGBClassifier(
            # use_label_encoder=True,
            eval_metric="auc",
            tree_method="hist",
            device="cuda",
        ),
        param_grid=param_grid,
        scoring=scoring,
        cv=cv,
        n_jobs=-1,
        verbose=2,
    )
    grid_search.fit(X, y, sample_weight=weight,
                    early_stopping_rounds=50,
                    )

    # Get the best n results
    results = grid_search.cv_results_
    top_n_idx = np.argsort(results["rank_test_score"])[:n]
    top_n_params = [results["params"][i] for i in top_n_idx]
    top_n_scores = results["mean_test_score"][top_n_idx]

    return top_n_params, top_n_scores, grid_search


# Example usage:
param_grid = {
    "n_estimators": [1200],
    "max_depth": [2, 3],
    "learning_rate": [0.1, 0.05],
    "random_state": [42],
    "gamma": [0, 0.1],
    "reg_alpha": [0, 0.2, 0.3, 0.4],
    "reg_lambda": [0.1, 1, 10],
}

best_n_params, best_n_score, grid_search = grid_search_xgb(
    train_data_preprocessed, train_target_drop, param_grid, train_class_weight
)

In [14]:
best_n_params, best_n_score

([{'learning_rate': 0.1, 'n_estimators': 300, 'random_state': 42},
  {'learning_rate': 0.1, 'n_estimators': 1100, 'random_state': 42},
  {'learning_rate': 0.1, 'n_estimators': 700, 'random_state': 42}],
 array([0.66605354, 0.65799061, 0.65771031]))

## prediction

In [27]:
# test_data = pd.read_csv("/home/zqy/learningFile/sichuan/zqy/temp/2024年四川省大学生数据科学与统计建模竞赛/测试集/test_data.csv")
test_data = pd.read_csv(os.path.join(REPO_PATH, "zqy", "temp", "test_data.csv"))

In [28]:
output_xgb = model_xgb.predict_proba(test_data_preprocessed)[:, 1]
output_xgb

array([0.4158016 , 0.5468987 , 0.65897787, ..., 0.27522784, 0.5395359 ,
       0.7281891 ], dtype=float32)

In [29]:
test_data.head(3)

idx        X0        X1        X2  X3  X4  X5  X6        X7        X8  ...  \
0   39  0.103231  0.115568  0.509177 NaN NaN NaN NaN  0.316906  0.665162  ...   
1   41  0.523825  0.903096  0.554800 NaN NaN NaN NaN  0.950219  0.980000  ...   
2   43  0.103231  0.739719  0.555546 NaN NaN NaN NaN  0.487031  0.463713  ...   

   X3796  X3797  X3798  X3799  X3800  X3801  X3802  X3803  X3804  X3805  
0    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
1    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  
2    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN  

[3 rows x 3807 columns]

In [30]:
output_xgb_pd = pd.DataFrame(output_xgb, columns=["y_pred"])
output_xgb_pd["idx"] = test_data["idx"]
output_xgb_pd = output_xgb_pd[["idx", "y_pred"]]
output_xgb_pd

idx    y_pred
0         39  0.415802
1         41  0.546899
2         43  0.658978
3         45  0.465110
4         55  0.595384
...      ...       ...
18129  79636  0.699781
18130  79637  0.197133
18131  79638  0.275228
18132  79640  0.539536
18133  79641  0.728189

[18134 rows x 2 columns]

In [31]:
output_xgb_pd.to_csv(
    os.path.join(REPO_PATH, "zqy", "output", "output_xgb_weight_together_params1.csv"),
    index=False,
    sep=",",
)

# xgboost regression date

## unit test

In [19]:
# load date data
train_date = train_target["date"].to_numpy()
train_date.max(), train_date.min()

(73, 1)

In [20]:
date_class_weight = {}
date_class_cnt = np.unique(train_date, return_counts=True)
for i in range(len(date_class_cnt[0])):
    date_class_weight[i] = date_class_cnt[1].sum() / date_class_cnt[1][i]
# date_class_weight, date_class_cnt

train_date_weight = np.zeros(train_target_drop.shape[0])
for i in range(len(date_class_cnt[0])):
    train_date_weight[train_date == date_class_cnt[0][i]] = date_class_weight[i]
train_date_weight.shape # train_date_weight can use in regression

(61866,)

In [21]:
# define train set and test set
(
    X_train,
    X_test,
    y_train,
    y_test,
    y_date_train,
    y_date_test,
    w_class_train,
    w_class_test,
    w_together_train,
    w_together_test,
    w_date_train,
    w_date_test,
) = train_test_split(
    train_data_preprocessed,
    train_target_drop,
    train_date,
    train_class_weight,
    train_together_weight,
    train_date_weight,
    test_size=0.2,
    random_state=11,
)

In [37]:
import xgboost as xgb

xgb_reg = xgb.XGBRegressor(
    n_estimators=1000,
    max_depth=6,
    learning_rate=0.1,
    objective="reg:squarederror",
    use_label_encoder=False,
    eval_metric=['rmse'],
    tree_method = "hist",
    device = "cuda",
    verbosity = 2,
)
xgb_reg.fit(X_train, y_date_train, eval_set=[(X_test, y_date_test)],
            sample_weight=w_date_train,
            # early_stopping_rounds=50,
            )


/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [00:09:31] WARNING: /workspace/src/context.cc:43: No visible GPU is found, setting device to CPU.
  warnings.warn(smsg, UserWarning)
/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [00:09:31] WARNING: /workspace/src/context.cc:196: XGBoost is not compiled with CUDA support.
  warnings.warn(smsg, UserWarning)
/home/zqy/venv/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [00:09:31] WARNING: /workspace/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


[0]	validation_0-rmse:23.71718
[1]	validation_0-rmse:22.81006
[2]	validation_0-rmse:21.95975
[3]	validation_0-rmse:21.32703
[4]	validation_0-rmse:20.59850
[5]	validation_0-rmse:20.14112
[6]	validation_0-rmse:19.42221
[7]	validation_0-rmse:18.93786
[8]	validation_0-rmse:18.57948
[9]	validation_0-rmse:18.22259
[10]	validation_0-rmse:17.76282
[11]	validation_0-rmse:17.41111
[12]	validation_0-rmse:17.19969
[13]	validation_0-rmse:16.98941
[14]	validation_0-rmse:16.79690
[15]	validation_0-rmse:16.62613
[16]	validation_0-rmse:16.47435
[17]	validation_0-rmse:16.34327
[18]	validation_0-rmse:16.21585
[19]	validation_0-rmse:16.10492
[20]	validation_0-rmse:15.99118
[21]	validation_0-rmse:15.89267
[22]	validation_0-rmse:15.74495
[23]	validation_0-rmse:15.65333
[24]	validation_0-rmse:15.48600
[25]	validation_0-rmse:15.33858
[26]	validation_0-rmse:15.27410
[27]	validation_0-rmse:15.14157
[28]	validation_0-rmse:15.04845
[29]	validation_0-rmse:14.94261
[30]	validation_0-rmse:14.88344
[31]	validation_0-

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device='cuda', early_stopping_rounds=None,
             enable_categorical=False, eval_metric=['rmse'], feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=6, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

## hyperparameters tuning

In [42]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

def grid_date_xgb(X, y, param_grid, weight, cv=5, scoring="neg_mean_squared_error", n=5):
    grid_search = GridSearchCV(
        estimator=xgb.XGBRegressor(
            eval_metric="rmse",
            tree_method="hist",
            device="cuda",
        ),
        param_grid=param_grid,
        scoring=scoring,
        cv=cv,
        n_jobs=-1,
        verbose=2,
    )
    grid_search.fit(X, y, sample_weight=weight,
                    # early_stopping_rounds=50, # maybe raise error?
                    )
    # Get the best n results
    results = grid_search.cv_results_
    top_n_idx = np.argsort(results["rank_test_score"])[:n]
    top_n_params = [results["params"][i] for i in top_n_idx]
    top_n_scores = results["mean_test_score"][top_n_idx]

    return top_n_params, top_n_scores, grid_search

def grid_date_lgb(X, y, param_grid, weight, cv=5, scoring="neg_mean_squared_error", n=5):
    grid_search = GridSearchCV(
        estimator=lgb.LGBMRegressor(
            objective="regression",
            metric="rmse",
            tree_method="hist",
            device="gpu",
        ),
        param_grid=param_grid,
        scoring=scoring,
        cv=cv,
        n_jobs=-1,
        verbose=2,
    )
    grid_search.fit(X, y, sample_weight=weight,
                    # early_stopping_rounds=50, # maybe raise error?
                    )
    # Get the best n results
    results = grid_search.cv_results_
    top_n_idx = np.argsort(results["rank_test_score"])[:n]
    top_n_params = [results["params"][i] for i in top_n_idx]
    top_n_scores = results["mean_test_score"][top_n_idx]

    return top_n_params, top_n_scores, grid_search


In [ ]:
param_grid_date = {
    "n_estimators": [1000],
    # "max_depth": [6, 7],
    # "learning_rate": [0.1, 0.05],
    "random_state": [42],
    # "gamma": [0, 0.1],
    # "reg_alpha": [0, 0.2, 0.3, 0.4],
    # "reg_lambda": [0.1, 1, 10],
}

top_n_params_date, top_n_scores_date, grid_search_date = grid_date_xgb(
    train_data_preprocessed, train_date, param_grid_date, train_date_weight
)
top_n_params_date, top_n_scores_date

Fitting 5 folds for each of 1 candidates, totalling 5 fits


## tuning based on sampling-date

In [23]:
# concat date to train data
train_concat_date = train_data_preprocessed.copy()
train_concat_date["date"] = train_date
train_concat_date.shape, train_data_preprocessed.shape

((61866, 3696), (61866, 3695))

In [ ]:
param_grid_concat = {
    "n_estimators": [1000],
    "max_depth": [6, 7],
    "learning_rate": [0.1, 0.05],
    "random_state": [42],
    "gamma": [0, 0.1],
    "reg_alpha": [0, 0.2, 0.3, 0.4],
    "reg_lambda": [0.1, 1, 10],
}

top_n_params_concat, top_n_scores_concat, grid_search_concat = grid_search_xgb(
    train_concat_date, train_target_drop, param_grid_concat, train_class_weight
)
top_n_params_concat, top_n_scores_concat