# load data

In [1]:
import os
import numpy as np
import pandas as pd

# if you use `ios` or `windows`, you need to change the `REPO_PATH` to your own path
REPO_PATH = "/home/zqy/learningFile/sichuan/"

train_data_preprocessed = pd.read_csv(
    os.path.join(REPO_PATH, "zqy", "temp", "train_data_fillna_drop_norm.csv")
)
test_data_preprocessed = pd.read_csv(
    os.path.join(REPO_PATH, "zqy", "temp", "test_data_fillna_drop_norm.csv")
)


In [2]:
train_data_preprocessed.shape, test_data_preprocessed.shape

((61866, 3695), (18134, 3695))

In [3]:
train_data_preprocessed.head(3)

X0        X1        X2   X3            X4            X5  \
0  1.709604 -0.364987 -1.562489  0.0  9.770206e-16  1.243610e-15   
1  1.709604 -0.364987 -0.859708  0.0  9.770206e-16  1.243610e-15   
2  1.333118 -1.432679 -1.588871  0.0  9.770206e-16  1.243610e-15   

             X6        X7        X8        X9  ...         X3796     X3797  \
0 -2.221561e+00 -1.618875 -1.514485 -1.218867  ...  1.956724e-15  0.000000   
1  8.961731e-16 -1.406030 -1.266209 -1.218867  ... -2.723617e+00 -2.784325   
2  8.961731e-16 -1.772480 -1.633739 -1.762651  ...  1.956724e-15  0.000000   

          X3798     X3799         X3800         X3801         X3802  \
0  5.428685e-16  0.000000 -1.630523e-15 -1.087010e-15 -1.621701e-15   
1  4.535885e+00  2.914316  3.404360e+00  4.161721e+00  3.311772e+00   
2  5.428685e-16  0.000000 -1.630523e-15 -1.087010e-15 -1.621701e-15   

          X3803         X3804         X3805  
0  1.620792e-15 -1.089747e-15 -1.104692e-15  
1  2.713803e+00  2.382499e+00  2.702521e+00  
2  1.620792e-15 -1.089747e-15 -1.104692e-15  

[3 rows x 3695 columns]

In [4]:
test_data_preprocessed.head(3)

X0        X1        X2   X3            X4            X5  \
0 -1.450864 -1.432679 -0.020007  0.0  9.770206e-16  1.243610e-15   
1  0.047310  1.381808  0.155341  0.0  9.770206e-16  1.243610e-15   
2 -1.450864  0.797930  0.158208  0.0  9.770206e-16  1.243610e-15   

             X6        X7        X8        X9  ...         X3796  X3797  \
0  8.961731e-16 -0.711873  0.503163  1.463917  ...  1.956724e-15    0.0   
1  8.961731e-16  1.521253  1.613779  1.189941  ...  1.956724e-15    0.0   
2  8.961731e-16 -0.111994 -0.207470 -0.235015  ...  1.956724e-15    0.0   

          X3798  X3799         X3800         X3801         X3802  \
0  5.428685e-16    0.0 -1.630523e-15 -1.087010e-15 -1.621701e-15   
1  5.428685e-16    0.0 -1.630523e-15 -1.087010e-15 -1.621701e-15   
2  5.428685e-16    0.0 -1.630523e-15 -1.087010e-15 -1.621701e-15   

          X3803         X3804         X3805  
0  1.620792e-15 -1.089747e-15 -1.104692e-15  
1  1.620792e-15 -1.089747e-15 -1.104692e-15  
2  1.620792e-15 -1.089747e-15 -1.104692e-15  

[3 rows x 3695 columns]

In [5]:
path = "zqy/temp/2024年四川省大学生数据科学与统计建模竞赛/训练集/train_target.csv"
train_target = pd.read_csv(os.path.join(REPO_PATH, path))
train_target

idx  date    y
0          0     7  0.0
1          1     7  0.0
2          2     8  0.0
3          3     7  0.0
4          4     7  0.0
...      ...   ...  ...
61861  79995    21  0.0
61862  79996    21  0.0
61863  79997    21  0.0
61864  79998    21  0.0
61865  79999    21  0.0

[61866 rows x 3 columns]

In [6]:
train_target_drop = train_target.drop(columns=["idx", "date"]).astype(int)
train_target_drop   

y
0      0
1      0
2      0
3      0
4      0
...   ..
61861  0
61862  0
61863  0
61864  0
61865  0

[61866 rows x 1 columns]

In [7]:
np.unique(train_target_drop.values, return_counts=True)

(array([0, 1]), array([50526, 11340]))

# MLP

In [20]:
import tensorflow as tf
import tensorflow.keras as keras

model = keras.Sequential([
    keras.layers.Dense(1800, activation='relu', input_shape=(train_data_preprocessed.shape[1],)),
    # keras.layers.Dense(5000, activation='relu'),
    keras.layers.Dense(2560, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1024, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(256, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dropout(0.2),
    # keras.layers.Dense(2, activation='softmax')
    keras.layers.Dense(1, activation='sigmoid')
])

model.summary()

/home/zqy/venv/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_15 (Dense)                │ (None, 1800)           │     6,652,800 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 2560)           │     4,610,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 2560)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 1024)           │     2,622,464 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 1024)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 256)            │       262,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 64)             │        16,448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 16)             │         1,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,165,729 (54.04 MB)

 Trainable params: 14,165,729 (54.04 MB)

 Non-trainable params: 0 (0.00 B)

In [21]:
class_weight = {}
class_cnt = np.unique(train_target_drop, return_counts=True)
for i in range(len(class_cnt[0])):
    class_weight[i] = class_cnt[1].sum() / class_cnt[1][i]
class_weight, class_cnt

({0: 1.2244389027431422, 1: 5.455555555555556},
 (array([0, 1]), array([50526, 11340])))

In [22]:
train_target_one_hot = pd.get_dummies(train_target_drop, columns=['y'])
train_target_one_hot = train_target_one_hot.values
train_target_one_hot = train_target_one_hot.astype(int)
train_target_one_hot, train_target_one_hot.shape, train_data_preprocessed.shape

(array([[1, 0],
        [1, 0],
        [1, 0],
        ...,
        [1, 0],
        [1, 0],
        [1, 0]]),
 (61866, 2),
 (61866, 3695))

In [26]:
from tensorflow.keras.metrics import AUC, F1Score

# Initialize the weights you want to set
initial_weights = [np.random.rand(*w.shape) for w in model.get_weights()]
model.set_weights(initial_weights)

model.compile(
    optimizer="adam",
    # loss=keras.losses.CategoricalCrossentropy(from_logits=False),
    loss=keras.losses.BinaryCrossentropy(from_logits=False),
    metrics=["accuracy", "auc", F1Score(average="micro"), F1Score(average="macro")],
)
model.fit(
    train_data_preprocessed,
    # train_target_one_hot,
    train_target_drop,
    epochs=60,
    shuffle=True,
    # class_weight=class_weight,
    batch_size=32,
    validation_split=0.2,
)

Epoch 1/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 90s 58ms/step - accuracy: 0.3289 - auc: 0.5010 - f1_score: 0.3046 - f1_score_1: 0.3046 - loss: 1686341248.0000 - val_accuracy: 0.8474 - val_auc: 0.5000 - val_f1_score: 0.0000e+00 - val_f1_score_1: 0.0000e+00 - val_loss: 7740903.0000
Epoch 2/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 89s 57ms/step - accuracy: 0.6638 - auc: 0.4998 - f1_score: 0.2113 - f1_score_1: 0.2113 - loss: 15511708.0000 - val_accuracy: 0.8474 - val_auc: 0.5000 - val_f1_score: 0.0000e+00 - val_f1_score_1: 0.0000e+00 - val_loss: 2179317.7500
Epoch 3/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 89s 57ms/step - accuracy: 0.6726 - auc: 0.5024 - f1_score: 0.2090 - f1_score_1: 0.2090 - loss: 4338165.0000 - val_accuracy: 0.8474 - val_auc: 0.5000 - val_f1_score: 0.0000e+00 - val_f1_score_1: 0.0000e+00 - val_loss: 600758.0000
Epoch 4/60
1547/1547 ━━━━━━━━━━━━━━━━━━━━ 89s 57ms/step - accuracy: 0.6694 - auc: 0.4979 - f1_score: 0.2030 - f1_score_1: 0.2030 - loss: 1128221.1250 - val_accuracy: 0.8474 - val_au

KeyboardInterrupt: 

## prediction

In [25]:
test_data = pd.read_csv("/home/zqy/learningFile/sichuan/zqy/temp/2024年四川省大学生数据科学与统计建模竞赛/测试集/test_data.csv")

In [26]:
# Predict the probabilities
predictions = model.predict(test_data_preprocessed)

# Convert probabilities to binary values (0 or 1) using a threshold of 0.5
binary_predictions = (predictions > 0.5).astype(int)

# Create a DataFrame with the results
output_binary = pd.DataFrame(binary_predictions, columns=["y_pred"])
output_binary["idx"] = test_data["idx"]
output_binary = output_binary[["idx", "y_pred"]]

567/567 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step


In [29]:
np.unique(output_binary.y_pred.values)

array([0])

In [21]:
output_pd.to_csv(
    os.path.join(REPO_PATH, "zqy", "output", "output.csv"),
    index=False,
    sep=",",
)

# XGBoost

In [29]:
import xgboost as xgb
dtrain = xgb.DMatrix(train_data_preprocessed, label=train_target_drop)

param = {
    'max_depth': 6,
    'eta': 0.3,
    'objective': 'binary:logistic',
    'eval_metric': ['logloss', 'auc', 'error'],
    'scale_pos_weight': class_weight[1] / class_weight[0]
}

num_round = 100
evals_result = {}
bst = xgb.train(param, dtrain, num_round, evals=[(dtrain, 'train')], evals_result=evals_result)

# Display the evaluation results
for metric in evals_result['train']:
    print(f"{metric}: {evals_result['train'][metric]}")



: 